sudo: required
language: minimal
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install: 
script:
- sh build.sh
deploy:
  provider: releases
  api_key:
    secure: "viDbC8aYSozUuEC6KTZz9oJIcwLqSD/vM0o8WeWnnrdTmJfFnt2meNaco6MWE4OcaJv9teS1nic4VzYY8rMtAWWs9nTEdWytuJiyXYbEzaquAnNlMwZT4szHVyDAHjcnkiFHGhhMqYjnsFpRfk8BzjLG5IrouKh5gyVSRTCsFR8hQeJXE6HlKBUC4uppZ/tghsXt5PeXSQH2zPWEotGpbojdO3CWHI2JXPjzqWYB976hkGUkDOx2p+YklldZ/apjkLWt9KwK9kl02TdtS+IXu1v5itIcg4rs320t50d96eUPAETznh3RPN5g62IRgMTnTA9I5TsHKvYLDgZYdvReF3Wex/qAVwLzYWcV4tf8Gwi7LAZQyixjXGgqY0kKZ594D16zwhJhmqmFtTnSJwsXulEStgsRfzLRiUMybq8M2lCfIHELi1mD2ANqXP8AfkJBu3+ZpYL0fEmH+4M1R+FOxlxvvTFd7Hj72bAPy9ccWCTmBi5SCiAapnpTbIeizMGc23fMrlnK0+aNE+gyIWqLEuqyic/SEoL89mToClxUcjVORTle4pRaEu+3fYRp8h4LVhvrLWeE6tG5xy7Pf2SFaj5EMeYbq6HiDh2gaTh6ZUW1uPn6RTRjMxOsTArq+deTeZWPu5buJz6A4etj8e3TqZbrVz71a+X9fggvKfIeQvs="
  file:
  - "./of-watchdog"
  - "./of-watchdog-armhf"
  - "./of-watchdog-arm64"
  - "./of-watchdog-darwin"
  - "./of-watchdog.exe"
  skip_cleanup: true
  on:
    tags: true
